site_name: Azimuth Science Platforms
repo_url: https://github.com/azimuth-cloud/azimuth-user-docs
copyright: |
  Copyright &copy; 2024 Azimuth</br>
edit_uri: ''
nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started/getting-started.md'
  - 'Platforms':
    - 'Linux Workstation': 'platforms/linux-workstation.md'
    - 'Jupyter Notebook': 'platforms/jupyter-notebook.md'
    - 'Slurm': 'platforms/slurm.md'
    - 'Kubernetes': 'platforms/kubernetes.md'
  - 'Kubernetes Applications': 
    - 'JupyterHub': 
      - 'Deploying JupyterHub': 'platforms/kubernetes-applications/jupyterhub.md'
      - 'GPU-Enabled Notebooks': 'platforms/kubernetes-applications/gpu-enabled-notebooks.md'
    - 'DaskHub':
      - 'Deploying DaskHub': 'platforms/kubernetes-applications/daskhub.md'
  - 'Usage': 'usage/usage.md'
  - 'Advanced':
    - 'Machines': 'advanced/machines.md'
    - 'Volumes': 'advanced/volumes.md'

theme:
  features:
    - navigation.tracking
  name: material
  logo: assets/images/azimuth-logo-white.png
  favicon: assets/images/azimuth-logo-white.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue grey
      accent: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: deep purple
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      
